### ISSUE TITLE
Should Ultrasonic work?

### ISSUE THREAD

**Issue by swalberg** [wpilibsuite/wpilib-ws-robot-romi#101]
I saw in #69 that some hardware support may be limited. Curious to know if I should expect [Ultrasonic](https://docs.wpilib.org/en/stable/docs/software/sensors/ultrasonics-software.html#ping-response-ultrasonics) sensors like the HC-SRO4 to work. It's just returning 0 for me. Thanks!

**Comment by zhiquanyeo** [comment]
The "ping" style ultrasonic sensors won't work with the Romi just yet. However, ultrasonic sensors like the Maxbotix ones that return an analog signal will be usable, same with the Sharp IR sensors

**Comment by swalberg** [comment]
Thanks! I'll look around for an analog sensor.
